### PR TITLE
Fix AMIGAOS4 compile/build

### PR DESCRIPTION
**Pull request by raziel-**
AmigaOS4 doesn't have mmap.h.

If i broke your coding guidelines (and i'm sure i did) please comment.

This is just so i have the changes up. I don't know what you are planning with the code, but it's nice to have it build again on my platform.

P.S: MIDI supoort would be really cool ;-)

### CODE REVIEW

**Comment by cyxx** [comment]
If mmap() is not available on AmigaOS, then I think a new class MemoryMappedFile_impl must be written. Your commit replaces mmap() call with malloc() but does not copy the file contents to newly allocated buffer, so I doubt this is working.

**Comment by raziel-** [comment]
Actually this works just fine on AmigaOS4.

I tried the changes locally before i put up the Pull Request.

**Comment by cyxx** [comment]
I think it works because that code is not used. The MemoryMappedFile_POSIX is only used if you have the datafiles bundled as "bs.dat". In case you use the original directory structure, this will not be a problem. The fix here is probably to add a compilation switch to support "bs.dat".

**Comment by raziel-** [comment]
Ok, so nothing i could do really?

btw: What exactly has changed since 0.1.4?

**Comment by cyxx** [comment]
The code has been reworked to avoid the dependency on mmap(), see a6df8a58.
0.1.5 changes are limited to fixes with the demo datafiles and changes for Emscripten (http://cyxx.github.io/bermuda/)

**Comment by raziel-** [comment]
Yes, with the changes it builds without problems again.

Would you keep the amigaos4 makefile, though?

**Comment by cyxx** [comment]
Good.
As I have no way to check the Amiga compilation, I woud prefer you maintain the Makefile in your own fork. Would that work ?

**Comment by raziel-** [comment]
Sure.

**Comment by cyxx** [comment]
Ok, then closing.

**Pull request closed without merging**
